/* automatically generated by ocaml-bindgen 0.0.1 */
#include "djinn_export.h"
#include <caml/alloc.h>
#include <caml/callback.h>
#include <caml/fail.h>
#include <caml/memory.h>
#include <caml/mlvalues.h>
#include <caml/unixsupport.h>
dummy* caml_dummy_of_value(value caml_x) {
  dummy* x = malloc(sizeof(struct dummy));
  x->a = Int_val(Field(caml_x, 0));
  x->b = Int_val(Field(caml_x, 1));
  x->c = Int_val(Field(caml_x, 2));
  return x;
}

value caml_dummy_to_value(struct dummy* x) {
  CAMLparam0();
  CAMLlocal1(caml_x);
  caml_x = caml_alloc_tuple(3);
  Store_field(caml_x, 0, Val_int(x->a));
  Store_field(caml_x, 1, Val_int(x->b));
  Store_field(caml_x, 2, Val_int(x->c));
  CAMLreturn(caml_x);
}

void caml_djinn_try_init(value caml_d) {
  CAMLparam1(caml_d);
  dummy* d = caml_dummy_of_value(caml_d);
  djinn_try_init(d);
  CAMLreturn0;
}

void caml_frame_begin(value caml_d) {
  CAMLparam1(caml_d);
  dummy* d = caml_dummy_of_value(caml_d);
  frame_begin(d);
  CAMLreturn0;
}

void caml_frame_end(value caml_d) {
  CAMLparam1(caml_d);
  dummy* d = caml_dummy_of_value(caml_d);
  frame_end(d);
  CAMLreturn0;
}

bool caml_window_should_close(value caml_d) {
  CAMLparam1(caml_d);
  CAMLlocal1(result);
  dummy* d = caml_dummy_of_value(caml_d);
  result = window_should_close(d);
  CAMLreturn(result);
}

params* caml_params_of_value(value caml_x) {
  params* x = malloc(sizeof(struct params));
  x->x = Int_val(Field(caml_x, 0));
  x->y = Int_val(Field(caml_x, 1));
  x->width = Int_val(Field(caml_x, 2));
  x->height = Int_val(Field(caml_x, 3));
  x->r = Double_val(Field(caml_x, 4));
  x->g = Double_val(Field(caml_x, 5));
  x->b = Double_val(Field(caml_x, 6));
  return x;
}

value caml_params_to_value(struct params* x) {
  CAMLparam0();
  CAMLlocal1(caml_x);
  caml_x = caml_alloc_tuple(7);
  Store_field(caml_x, 0, Val_int(x->x));
  Store_field(caml_x, 1, Val_int(x->y));
  Store_field(caml_x, 2, Val_int(x->width));
  Store_field(caml_x, 3, Val_int(x->height));
  Store_field(caml_x, 4, caml_copy_double(x->r));
  Store_field(caml_x, 5, caml_copy_double(x->g));
  Store_field(caml_x, 6, caml_copy_double(x->b));
  CAMLreturn(caml_x);
}

void caml_draw_rectangle(value caml_params) {
  CAMLparam1(caml_params);
  params* params = caml_params_of_value(caml_params);
  draw_rectangle(params);
  CAMLreturn0;
}


