/* automatically generated by ocaml-bindgen 0.0.1 */
#include "djinn_export.h"
#include <caml/alloc.h>
#include <caml/callback.h>
#include <caml/fail.h>
#include <caml/memory.h>
#include <caml/mlvalues.h>
#include <caml/unixsupport.h>
void caml_djinn_try_init() {
  CAMLparam0();
  djinn_try_init();
  CAMLreturn0;
}

void caml_frame_begin() {
  CAMLparam0();
  frame_begin();
  CAMLreturn0;
}

void caml_frame_end() {
  CAMLparam0();
  frame_end();
  CAMLreturn0;
}

bool caml_window_should_close() {
  CAMLparam0();
  CAMLlocal1(result);
  result = window_should_close();
  CAMLreturn(result);
}

box_params* caml_box_params_of_value(value caml_x) {
  box_params* x = malloc(sizeof(struct box_params));
  x->x = Int_val(Field(caml_x, 0));
  x->y = Int_val(Field(caml_x, 1));
  x->width = Int_val(Field(caml_x, 2));
  x->height = Int_val(Field(caml_x, 3));
  x->r = Double_val(Field(caml_x, 4));
  x->g = Double_val(Field(caml_x, 5));
  x->b = Double_val(Field(caml_x, 6));
  return x;
}

value caml_box_params_to_value(struct box_params* x) {
  CAMLparam0();
  CAMLlocal1(caml_x);
  caml_x = caml_alloc_tuple(7);
  Store_field(caml_x, 0, Val_int(x->x));
  Store_field(caml_x, 1, Val_int(x->y));
  Store_field(caml_x, 2, Val_int(x->width));
  Store_field(caml_x, 3, Val_int(x->height));
  Store_field(caml_x, 4, caml_copy_double(x->r));
  Store_field(caml_x, 5, caml_copy_double(x->g));
  Store_field(caml_x, 6, caml_copy_double(x->b));
  CAMLreturn(caml_x);
}

text_params* caml_text_params_of_value(value caml_x) {
  text_params* x = malloc(sizeof(struct text_params));
  x->x = Int_val(Field(caml_x, 0));
  x->y = Int_val(Field(caml_x, 1));
  x->r = Double_val(Field(caml_x, 2));
  x->g = Double_val(Field(caml_x, 3));
  x->b = Double_val(Field(caml_x, 4));
  return x;
}

value caml_text_params_to_value(struct text_params* x) {
  CAMLparam0();
  CAMLlocal1(caml_x);
  caml_x = caml_alloc_tuple(5);
  Store_field(caml_x, 0, Val_int(x->x));
  Store_field(caml_x, 1, Val_int(x->y));
  Store_field(caml_x, 2, caml_copy_double(x->r));
  Store_field(caml_x, 3, caml_copy_double(x->g));
  Store_field(caml_x, 4, caml_copy_double(x->b));
  CAMLreturn(caml_x);
}

void caml_draw_rectangle(value caml_params) {
  CAMLparam1(caml_params);
  box_params* params = caml_box_params_of_value(caml_params);
  draw_rectangle(params);
  CAMLreturn0;
}

void caml_draw_text_string(value caml_params) {
  CAMLparam1(caml_params);
  text_params* params = caml_text_params_of_value(caml_params);
  draw_text_string(params);
  CAMLreturn0;
}

int caml_get_mouse_x() {
  CAMLparam0();
  CAMLlocal1(result);
  result = get_mouse_x();
  CAMLreturn(result);
}

int caml_get_mouse_y() {
  CAMLparam0();
  CAMLlocal1(result);
  result = get_mouse_y();
  CAMLreturn(result);
}

bool caml_get_left_btn() {
  CAMLparam0();
  CAMLlocal1(result);
  result = get_left_btn();
  CAMLreturn(result);
}

bool caml_get_prev_left_btn() {
  CAMLparam0();
  CAMLlocal1(result);
  result = get_prev_left_btn();
  CAMLreturn(result);
}


