(* automatically generated by ocaml-bindgen 0.0.1 *)
type nonrec dummy = {
  a: int ;
  b: int ;
  c: int }
external djinn_try_init : d:dummy -> unit = "caml_djinn_try_init"
external frame_begin : d:dummy -> unit = "caml_frame_begin"
external frame_end : d:dummy -> unit = "caml_frame_end"
external window_should_close : d:dummy -> bool = "caml_window_should_close"
type nonrec params =
  {
  x: int ;
  y: int ;
  width: int ;
  height: int ;
  r: float ;
  g: float ;
  b: float }
external draw_rectangle : params:params -> unit = "caml_draw_rectangle"
